// pipeline{
//     agent {
//         docker{
//             image 'cypress/browsers:24.11.1'
//             //image 'cypress/browsers:node-24.11.1-chrome-142.0.7444.162-1-ff-145.0-edge-142.0.3595.65-1'
//             args '--entrypoint=""'
//         }
//     }
//     stages{
//         stage('install Dependencies'){
//             steps{
//                 sh 'npm install'
//             }
//         }
//         stage('Install '){
//             steps{
//                 sh 'npm install'
//             }
//         }

//         stage('Run Tests'){
//             steps{
//                 sh '.cypress/e2e/batchs/login_only.sh'
//             }
//         }
//     }
// }

pipeline {
    agent any  // On utilise l'agent par défaut pour gérer Docker manuellement

    environment {
        CYPRESS_IMAGE = 'cypress/browsers:24.11.1'
    }

    stages {
        stage('Install Dependencies & Run Tests') {
            steps {
                script {
                    // On récupère le chemin absolu du workspace
                    def workspaceDir = pwd()

                    // Lancer le container Docker avec le workspace monté correctement
                    docker.image(env.CYPRESS_IMAGE).inside("-v ${workspaceDir}:${workspaceDir} -w ${workspaceDir}") {
                        // Installer les dépendances
                        sh 'npm install'

                        // Exécuter le script Cypress
                        sh '.cypress/e2e/batchs/login_only.sh'
                    }
                }
            }
        }
    }
}
